/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.37
 * Generated at: 2020-08-31 20:41:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class musicUDatabase_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

	ResultSet rs = (ResultSet)request.getAttribute("table");

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Database</title>\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\">\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\n");
      out.write("  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\n");
      out.write("  <style>\n");
      out.write("\t#player{\n");
      out.write("\t\tposition:fixed;\n");
      out.write("\t\tbottom:0%;\n");
      out.write("\t\tleft:0%;\n");
      out.write("\t\twidth:100%;\n");
      out.write("\t\theight:100px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("  </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<nav class=\"navbar navbar-inverse\">\n");
      out.write("  <div class=\"container-fluid\">\n");
      out.write("    <div class=\"navbar-header\">\n");
      out.write("      <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#myNavbar\">\n");
      out.write("        <span class=\"icon-bar\"></span>\n");
      out.write("        <span class=\"icon-bar\"></span>\n");
      out.write("        <span class=\"icon-bar\"></span>                        \n");
      out.write("      </button>\n");
      out.write("      \n");
      out.write("      <a class=\"navbar-brand\" href=\"#\">HiveMusic</a>\n");
      out.write("     \n");
      out.write("    </div>\n");
      out.write("      <ul class=\"nav navbar-nav\">\n");
      out.write("        <li><a href=\"getmusicUController\">Home</a></li>\n");
      out.write("        <li><a href=\"\">Wishlist</a></li>\n");
      out.write("      </ul>\n");
      out.write("      <ul class=\"nav navbar-nav navbar-right\">\n");
      out.write("        <li><a href=\"logout.jsp\"><span class=\"glyphicon glyphicon-log-in\"></span> Logout</a></li>\n");
      out.write("      </ul>\n");
      out.write("    </div>\n");
      out.write(" \n");
      out.write("</nav>\n");
      out.write(" <div class=\"container\">\n");
      out.write("  <br>\n");
      out.write("  <h2>Enjoy the Musics</h2>\n");
      out.write("  <p>Type something in the input field to search the table for songs, categories or language:</p>  \n");
      out.write("  <input class=\"form-control\" id=\"myInput\" type=\"text\" placeholder=\"Search..\">\n");
      out.write("  <br> \n");
      out.write("  <table class=\"table table-hover\">\n");
      out.write("    <thead>\n");
      out.write("      <tr>\n");
      out.write("        <th>Song</th>\n");
      out.write("        <th>Category</th>\n");
      out.write("        <th>Language</th>\n");
      out.write("        <th>Track</th>\n");
      out.write("        <th>Wishlist</th>\n");
      out.write("        <th>Download</th>\n");
      out.write("      </tr>\n");
      out.write("    </thead>\n");
      out.write("    \n");
      out.write("    <tbody id=\"myTable\">\n");
      out.write("    ");
while(rs.next()) { 
    
      out.write("\n");
      out.write("      <tr id=\"");
      out.print(rs.getString("id"));
      out.write("\" class=\"trowz\" >\n");
      out.write("        <td>");
      out.print(rs.getString("music_name") );
      out.write("</td>\n");
      out.write("        <td>");
      out.print(rs.getString("category") );
      out.write("</td>\n");
      out.write("        <td>");
      out.print(rs.getString("language") );
      out.write("</td>\n");
      out.write("        <td><button  class=\"btn btn-primary play\" data-path=\"");
      out.print(rs.getString("path"));
      out.write("\" >Play</button> </td>\n");
      out.write("        <td>\n");
      out.write("        \t<button  class=\"btn btn-primary wish\" >Add</button> \n");
      out.write("        </td>\n");
      out.write("        <td>\n");
      out.write("        </td>\n");
      out.write("      </tr>\n");
      out.write("      ");
} 
      out.write("\n");
      out.write("    </tbody>\n");
      out.write("  </table>\n");
      out.write("  </div>\n");
      out.write("  <div id=\"aud\">\n");
      out.write("  <audio controls id=\"player\">\n");
      out.write("  \t\t\t<source src=\"\" type=\"audio/mpeg\">\n");
      out.write("  </audio>\n");
      out.write("  </div>\n");
      out.write("  <script>\n");
      out.write("\t$(document).ready(function(){\n");
      out.write("  \t$(\"#myInput\").on(\"keyup\", function() {\n");
      out.write("    var value = $(this).val().toLowerCase();\n");
      out.write("    $(\"#myTable tr\").filter(function() {\n");
      out.write("     $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)\n");
      out.write("    \t\t});\n");
      out.write("  \t\t});\n");
      out.write("\t});\n");
      out.write("\n");
      out.write("\t$(document).ready(function(){\n");
      out.write("\t  \t$(\".wish\").click(function() { \n");
      out.write("\t  \t    if ($(this).text() == \"Add\") { \n");
      out.write("\t  \t        $(this).text(\"Remove\"); \n");
      out.write("\t  \t    } else { \n");
      out.write("\t  \t        $(this).text(\"Add\"); \n");
      out.write("\t  \t    }; \n");
      out.write("\t\t\t\n");
      out.write("\t\t\t});\n");
      out.write("\t});\n");
      out.write("\t$(document).ready(function(){ \t\n");
      out.write("\t  \t$(\".play\").click(function(){\n");
      out.write("\t\t  \tif($(this).text()==\"Play\")\n");
      out.write("\t\t\t  \t{\n");
      out.write("\t\t\t  \t$(\".play\").text(\"Play\");\n");
      out.write("\t\t\t\t$(this).text(\"Stop\");\n");
      out.write("\t\t\t\tvar path = $(this).attr(\"data-path\");\n");
      out.write("\t\t\t\t$(\"#player\").attr(\"src\",path);\n");
      out.write("\t\t\t\t$(\"#player\").attr(\"autoplay\",\"true\");\n");
      out.write("\t\t\t\t$(\"#player\").load();\n");
      out.write("\t\t\t  \t}\n");
      out.write("\t\t  \telse\n");
      out.write("\t\t\t  \t{\n");
      out.write("\t\t  \t\t$(\"#player\").attr(\"src\",\"\");\n");
      out.write("\t\t  \t\t$(this).text(\"Play\");\n");
      out.write("\t\t\t  \t}\n");
      out.write("\t\t\t});\n");
      out.write("\t});\n");
      out.write("\t</script>\n");
      out.write("\t<!-- });\n");
      out.write("\t$(document).ready(function(){\n");
      out.write("  \t$(\".wish\").click(function() { \n");
      out.write("  \t    if ($(this).text() == \"Add\") { \n");
      out.write("  \t        $(this).text(\"Remove\"); \n");
      out.write("  \t    } else { \n");
      out.write("  \t        $(this).text(\"Add\"); \n");
      out.write("  \t    }; \n");
      out.write("\t\t\n");
      out.write("\t  \t  });-->\n");
      out.write("  \t<!--$('.icon-wishlist').on('click', function(){\n");
      out.write("  \t  $(this).toggleClass('in-wishlist');\n");
      out.write("  \t});-->\n");
      out.write("\n");
      out.write("\t<!--$(document).ready(function(){ \t\n");
      out.write("  \t$(\".play\").click(function(){\n");
      out.write("\t\t$(this).text(\"Stop\");\n");
      out.write("\t\t});\n");
      out.write("\t});-->\n");
      out.write("\t\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
